services:
  postgres:
    image: postgres:15-alpine
    container_name: printer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: printerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  printer-app:
    build: .
    container_name: printer_service_manager
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/printerdb?schema=public
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: